package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// overridePath returns the override for a shipped file, or "".
func overridePath(name string) string {
	p := filepath.Join(configDir, name)
	if isFile(p) {
		return p
	}
	return ""
}

// configBytes returns the effective content of settings.json, plugins.txt or
// mcp.json: the override if present, else the embedded default, else nothing.
func configBytes(name string) ([]byte, bool) {
	if p := overridePath(name); p != "" {
		if b, err := os.ReadFile(p); err == nil {
			return b, true
		}
	}
	b, err := assets.ReadFile(name)
	if err != nil {
		return nil, false
	}
	return b, true
}

var domainRe = regexp.MustCompile(`^\.?[A-Za-z0-9-]+(\.[A-Za-z0-9-]+)*$`)

// domainLines strips comments and whitespace and splits lines into domains
// and rejects.
func domainLines(b []byte) (good, bad []string) {
	for _, line := range strings.Split(string(b), "\n") {
		if i := strings.Index(line, "#"); i >= 0 {
			line = line[:i]
		}
		line = strings.Join(strings.Fields(line), "")
		switch {
		case line == "":
		case domainRe.MatchString(line):
			good = append(good, line)
		default:
			bad = append(bad, line)
		}
	}
	return
}

// allowlistDir writes the merged allowlist for a project and returns the
// directory holding it. Sources, in order: the shipped list, the user's
// override, the repo's own .moat/allowlist.txt. Only domain-shaped lines
// survive; the repo's contribution is announced every time so a cloned repo
// cannot widen egress unnoticed.
func allowlistDir(name, primary string) (string, error) {
	dir := filepath.Join(stateDir, name)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	shipped, _ := assets.ReadFile("proxy/allowlist.txt")
	type src struct {
		label string
		data  []byte
	}
	sources := []src{{"shipped allowlist", shipped}}
	userFile := filepath.Join(configDir, "allowlist.txt")
	repoFile := filepath.Join(primary, ".moat", "allowlist.txt")
	for _, f := range []string{userFile, repoFile} {
		if b, err := os.ReadFile(f); err == nil {
			sources = append(sources, src{f, b})
		}
	}
	seen := map[string]bool{}
	var out strings.Builder
	fmt.Fprintf(&out, "# generated by moat for %s from:\n", name)
	for _, s := range sources {
		fmt.Fprintf(&out, "#   %s\n", s.label)
	}
	for _, s := range sources {
		good, bad := domainLines(s.data)
		for _, l := range bad {
			info("warning: ignored non-domain line in %s: %s", s.label, l)
		}
		for _, d := range good {
			if !seen[d] {
				seen[d] = true
				out.WriteString(d + "\n")
			}
		}
		if s.label == repoFile {
			info("repo allowlist %s adds: %s", repoFile, strings.Join(good, " "))
		}
	}
	return dir, os.WriteFile(filepath.Join(dir, "allowlist.txt"), []byte(out.String()), 0o644)
}

func cmdConfig(args []string) error {
	sub := "path"
	if len(args) > 0 {
		sub = args[0]
	}
	switch sub {
	case "path":
		fmt.Println(configDir)
	case "init":
		if err := os.MkdirAll(configDir, 0o755); err != nil {
			return err
		}
		for _, f := range []string{"settings.json", "plugins.txt"} {
			p := filepath.Join(configDir, f)
			if isFile(p) {
				continue
			}
			b, _ := assets.ReadFile(f)
			if err := os.WriteFile(p, b, 0o644); err != nil {
				return err
			}
			info("created %s (copy of the shipped file)", p)
		}
		p := filepath.Join(configDir, "allowlist.txt")
		if !isFile(p) {
			hdr := "# Extra domains, merged with the shipped allowlist. One per line; .example.com matches subdomains.\n"
			if err := os.WriteFile(p, []byte(hdr), 0o644); err != nil {
				return err
			}
			info("created %s", p)
		}
		info("edit the files, then: moat reload")
	case "show":
		fmt.Printf("config dir:   %s\nstate dir:    %s\n", configDir, stateDir)
		for _, f := range []string{"settings.json", "plugins.txt", "mcp.json"} {
			switch {
			case overridePath(f) != "":
				fmt.Printf("%-13s %s\n", f, overridePath(f))
			case f != "mcp.json":
				fmt.Printf("%-13s (shipped)\n", f)
			default:
				fmt.Printf("%-13s (none)\n", f)
			}
		}
		fmt.Println("allowlist:    (shipped)")
		if isFile(filepath.Join(configDir, "allowlist.txt")) {
			fmt.Printf("              + %s\n", filepath.Join(configDir, "allowlist.txt"))
		}
		fmt.Println("              + <repo>/.moat/allowlist.txt when present")
	default:
		return fmt.Errorf("usage: moat config [path|init|show]")
	}
	return nil
}
