#!/usr/bin/env bash
# Shared by sandbox.sh and docker-sandbox.sh. Sourced, never executed.
# The caller sets HERE (this directory) and TOOL (name used in messages).

die()  { printf '%s: %s\n' "${TOOL:-sandbox}" "$*" >&2; exit 1; }
info() { printf '%s\n' "$*" >&2; }
need() { command -v "$1" >/dev/null 2>&1 || die "$1 not found"; }

# Configuration, highest precedence first:
#   <repo>/.claude-sandbox/allowlist.txt   extra domains for that repo only
#   $CLAUDE_SANDBOX_CONFIG/<file>          your overrides (default ~/.config/claude-sandbox)
#   claude-containers/<file>               shipped defaults
# settings.json, plugins.txt and mcp.json are replaced as a whole by an override;
# allowlist.txt files are merged. Merged allowlists are written per project to
# $CLAUDE_SANDBOX_STATE (default ~/.local/state/claude-sandbox).
CONFIG_DIR="${CLAUDE_SANDBOX_CONFIG:-${XDG_CONFIG_HOME:-$HOME/.config}/claude-sandbox}"
STATE_DIR="${CLAUDE_SANDBOX_STATE:-${XDG_STATE_HOME:-$HOME/.local/state}/claude-sandbox}"

# cfg <file>: the override if present, else the shipped default (may not exist).
cfg() {
  if [ -f "$CONFIG_DIR/$1" ]; then printf '%s' "$CONFIG_DIR/$1"; else printf '%s' "$HERE/$1"; fi
}
SETTINGS="$(cfg settings.json)"
PLUGINS="$(cfg plugins.txt)"
MCP="$(cfg mcp.json)"
HOOK="$HERE/sandbox/audit-hook.sh"

# allowlist_dir <name> <primary>: write the merged allowlist for a project and
# print the directory holding it. Comments, blanks and duplicates are dropped.
allowlist_dir() {
  local name="$1" primary="$2" dir="$STATE_DIR/$1" f
  local sources=("$HERE/proxy/allowlist.txt" "$CONFIG_DIR/allowlist.txt" "$primary/.claude-sandbox/allowlist.txt")
  mkdir -p "$dir"
  {
    echo "# generated by ${TOOL:-sandbox} for $name from:"
    for f in "${sources[@]}"; do [ -f "$f" ] && echo "#   $f"; done
    for f in "${sources[@]}"; do [ -f "$f" ] && sed -e 's/#.*//' -e 's/[[:space:]]//g' "$f"; done | awk 'NF && !seen[$0]++'
  } > "$dir/allowlist.txt"
  printf '%s' "$dir"
}

# Claude Code OAuth token, in this order: CLAUDE_CODE_OAUTH_TOKEN in the
# environment (from `claude setup-token`), the macOS keychain, then the
# credentials file Claude Code writes on Linux and WSL.
oauth_token() {
  if [ -n "${CLAUDE_CODE_OAUTH_TOKEN:-}" ]; then printf '%s' "$CLAUDE_CODE_OAUTH_TOKEN"; return; fi
  local json="" file="${CLAUDE_CONFIG_DIR:-$HOME/.claude}/.credentials.json"
  if [ "$(uname -s)" = Darwin ] && command -v security >/dev/null 2>&1; then
    json="$(security find-generic-password -s "Claude Code-credentials" -w 2>/dev/null || true)"
  fi
  if [ -z "$json" ] && [ -f "$file" ]; then json="$(cat "$file")"; fi
  [ -n "$json" ] || die "no Claude Code credentials found: run claude on the host and log in, or export CLAUDE_CODE_OAUTH_TOKEN from 'claude setup-token'"
  printf '%s' "$json" | extract_token || die "could not read claudeAiOauth.accessToken from the Claude Code credentials"
}
extract_token() {
  if command -v jq >/dev/null 2>&1; then jq -er '.claudeAiOauth.accessToken'
  else python3 -c 'import sys, json; print(json.load(sys.stdin)["claudeAiOauth"]["accessToken"])'; fi
}

# Git identity for commits made inside the sandbox, resolved on the host from
# the workspace's effective config (repo, then global). Fills GIT_ENV.
GIT_ENV=()
git_identity_env() {
  local ws="$1" name email
  GIT_ENV=()
  name="$(git -C "$ws" config --get user.name 2>/dev/null || true)"
  email="$(git -C "$ws" config --get user.email 2>/dev/null || true)"
  [ -n "$name" ]  && GIT_ENV+=(-e "GIT_AUTHOR_NAME=$name"   -e "GIT_COMMITTER_NAME=$name")
  [ -n "$email" ] && GIT_ENV+=(-e "GIT_AUTHOR_EMAIL=$email" -e "GIT_COMMITTER_EMAIL=$email")
  return 0
}

# Host timezone for the image: TZ, else /etc/localtime, else /etc/timezone, else UTC.
host_tz() {
  if [ -n "${TZ:-}" ]; then printf '%s' "$TZ"; return; fi
  local l; l="$(readlink /etc/localtime 2>/dev/null || true)"
  case "$l" in *zoneinfo/*) printf '%s' "${l#*zoneinfo/}"; return ;; esac
  if [ -s /etc/timezone ]; then tr -d '[:space:]' < /etc/timezone; return; fi
  printf 'UTC'
}

# Per-run overrides for the claude command: --model M, --effort E, --mode P
# (or CLAUDE_SANDBOX_MODEL / _EFFORT / _MODE). Persistent defaults live in
# settings.json as model, effortLevel and permissions.defaultMode. Fills
# CLAUDE_ARGS with the matching claude flags and REST with everything else.
CLAUDE_ARGS=(); REST=()
parse_claude_opts() {
  local model="${CLAUDE_SANDBOX_MODEL:-}" effort="${CLAUDE_SANDBOX_EFFORT:-}" mode="${CLAUDE_SANDBOX_MODE:-}"
  CLAUDE_ARGS=(); REST=()
  while [ $# -gt 0 ]; do
    case "$1" in
      --model|--effort|--mode) [ $# -ge 2 ] || die "$1 needs a value" ;;
    esac
    case "$1" in
      --model)    model="$2";  shift 2 ;;
      --effort)   effort="$2"; shift 2 ;;
      --mode)     mode="$2";   shift 2 ;;
      --model=*)  model="${1#*=}";  shift ;;
      --effort=*) effort="${1#*=}"; shift ;;
      --mode=*)   mode="${1#*=}";   shift ;;
      *) REST+=("$1"); shift ;;
    esac
  done
  [ -n "$model" ]  && CLAUDE_ARGS+=(--model "$model")
  [ -n "$effort" ] && CLAUDE_ARGS+=(--effort "$effort")
  [ -n "$mode" ]   && CLAUDE_ARGS+=(--permission-mode "$mode")
  return 0
}

# Print the safe.directory entries to add inside a container for the given paths.
git_safe_dirs() {  # container [path ...]
  local c="$1"; shift
  [ $# -gt 0 ] || return 0
  docker exec "$c" sh -c '
    for d in "$@"; do
      git config --global --get-all safe.directory 2>/dev/null | grep -qx "$d" || git config --global --add safe.directory "$d"
    done' _ "$@"
}
